### ISSUE TITLE
Remove the yellow border

### ISSUE THREAD

**Issue by cloudor126** [robmikh/wgctest#4]
I'm learning your demo codes and trying to write a similar util for my friends. I want to remove the yellow border around the target window being captured. I noticed that the session of `GraphicsCaptureSession` object has a method:
`pub fn SetIsBorderRequired(&self, value: bool) -> ::windows::core::Result`

But I failed to make use of that method. Can you make your demo have an option to remove the border?

**Comment by robmikh** [comment]
These APIs are implemented by the operating system, and thus the version of the OS you're running on will influence what features you have access to at runtime.

In this case, the `IsBorderRequired` property was introduced in Windows 10 build 10.0.20348. You can see that listed on the property's MSDN page: https://learn.microsoft.com/en-us/uwp/api/windows.graphics.capture.graphicscapturesession.isborderrequired?view=winrt-22621

If you're running on build 10.0.20348 or higher, then you can set the property properly. Practically speaking, general consumers saw this feature introduced as part of Windows 11. You can use the `ApiInformation` API to check to see if the property is available or not at runtime. 

The [Win32CaptureSample](https://github.com/robmikh/Win32CaptureSample) project shows how to do this, although it's written in C++ instead of Rust. But it should be straightforward to port. Here is a [section of code that calls GraphicsCaptureAccess to get access to the property](https://github.com/robmikh/Win32CaptureSample/blob/d5c1afb164147c983c078bf9b9e596cc9589db0c/Win32CaptureSample/App.cpp#L253-L263) and here's a [section that checks to see if the property is available](https://github.com/robmikh/Win32CaptureSample/blob/d5c1afb164147c983c078bf9b9e596cc9589db0c/Win32CaptureSample/SampleWindow.cpp#L223-L224).
